### PR TITLE
Update to vips8

### PR DESCRIPTION
**Pull request by automata**
Create a new bundle (with updated `build.sh`) using libvips 8.1.1 which makes it possible to load GIF buffers (thanks to ImageMagick lib).

### CODE REVIEW

**Comment by automata** [comment]
:warning: Do not merge :warning: 

Please ignore this PR, it only contains some suggestions and updated bundle.

**Comment by alex88** [comment]
Hi @automata! Thanks a lot for this! So for now there is no tiff support? Do you use vips buildpack in production?

**Comment by automata** [comment]
@alex88 no libtiff included but thanks to opencv buildpack we're using, we have tiff support thanks to that. Yes, we're using the buildpack in production. Maybe a nice quick thing to do on yours is to remove `share/{doc,gtk-doc}` to decrease file size a bit (around 30 MB).

**Comment by alex88** [comment]
Well, 30 MB seems quite some space since we've to download the buildpack on every deploy, thanks a lot for this, I'm going to implement it during this week!

**Pull request closed without merging**
